// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmpT-T7VCvh6lqxq1RD249eQvV5Be7QD4',
    appId: '1:354429157919:web:1c8480d93eb008a4c30b2a',
    messagingSenderId: '354429157919',
    projectId: 'sample-crud-4ec0b',
    authDomain: 'sample-crud-4ec0b.firebaseapp.com',
    storageBucket: 'sample-crud-4ec0b.appspot.com',
    measurementId: 'G-W0EZZSPWR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv7xP_S5EX5DAxDc5uCVl9A5WhpNF7CHA',
    appId: '1:354429157919:android:bbd12097f4fdf87bc30b2a',
    messagingSenderId: '354429157919',
    projectId: 'sample-crud-4ec0b',
    storageBucket: 'sample-crud-4ec0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWpSrRyQcED-E4jhRT5rlUul3KyHC-kmE',
    appId: '1:354429157919:ios:0f821c3a99175f52c30b2a',
    messagingSenderId: '354429157919',
    projectId: 'sample-crud-4ec0b',
    storageBucket: 'sample-crud-4ec0b.appspot.com',
    iosClientId: '354429157919-s4r77vsi1og0hdieg1annudllb08ur9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWpSrRyQcED-E4jhRT5rlUul3KyHC-kmE',
    appId: '1:354429157919:ios:0f821c3a99175f52c30b2a',
    messagingSenderId: '354429157919',
    projectId: 'sample-crud-4ec0b',
    storageBucket: 'sample-crud-4ec0b.appspot.com',
    iosClientId: '354429157919-s4r77vsi1og0hdieg1annudllb08ur9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );
}
